### ISSUE TITLE
Diseño de algoritmos - Aquino

### ISSUE THREAD

**Issue by MrPool702** [MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997#2]
Se puede realizar en cualquier artefacto de diseño de algoritmos

**Comment by Fernando213X** [comment]
import math
import pandas as pd
import numpy as np
import heapq as hq

def Dikjstra_(G,inicio):
  n=len(G)
  visited=[False]*n
  path=[None]*n
  visited[inicio]=True
  cost=[math.inf]*n
  cost[inicio]=0
  queue=[(0,inicio)]
  while queue:
    g_u,u = hq.heappop(queue)
    for v,w in G[u]:
      f = g_u + w
      if f < cost[v]:
        cost[v]=f
        path[v]=u
        hq.heappush(queue,(f,v))

  return cost

**Comment by Fernando213X** [comment]
### Dijkstra
`import math
import pandas as pd
import numpy as np
import heapq as hq

def Dijkstra(G,inicio,costo_final):
  n=len(G)
  visited=[False]*n
  path=[None]*n
  visited[inicio]=True
  cost=[math.inf]*n
  cost[inicio]=0
  queue=[(0,inicio)]
  while queue:
    g_u,u = hq.heappop(queue)
    for v,w in G[u]:
      costo_final = g_u + w
      if costo_final < cost[v]:
        cost[v]=costo_final
        path[v]=u
        hq.heappush(queue,(costo_final,v))

  return cost, costo_final
`

**Comment by Fernando213X** [comment]
<img src="https://github.com/MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997/blob/main/TestMap.png?raw=true" alt="City Map" width="300px">
