### ISSUE TITLE
Binary Partition Tree Test

### ISSUE THREAD

**Issue by MrPool702** [MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997#5]

**Comment by Miguel445Ar** [comment]
### Primera prueba de modelado de una ciudad de prueba
[https://colab.research.google.com/drive/1fogU0MtutCTepoIyB6H1MUqNGb5cFjf4#scrollTo=2es_KaWtAm64&line=37&uniqifier=1](url)

**Comment by Miguel445Ar** [comment]
Miss click

**Comment by Miguel445Ar** [comment]
> ### Primera prueba de generacion de una ciudad

`import random
import matplotlib.pyplot as plt
n = 800
arr = [[7]*n for i in range(n)]
def drawMaze(maze):
  _, ax = plt.subplots(figsize=(18, 18))
  ax.imshow(maze)
  ax.axis("off")
def partitionTree2(arr,rowI,rowF,colI,colF,corners):
    callStack = [(rowI,rowF,colI,colF)]
    while callStack:
        ri, rf, ci, cf = callStack.pop()
        dif1 = cf - ci
        dif2 = rf -  ri
        for a in range(ci,cf):
            arr[ri][a] = 1
            arr[rf][a] = 1
        for b in range(ri,rf):
            arr[b][ci] = 1
            arr[b][cf] = 1
        if dif1 >= random.randint(20,30):
            mid = (ci + cf)//2
            arr[ri][mid] = 0
            arr[rf][mid] = 0
            corners.append((ri,mid))
            corners.append((rf,mid))
            callStack.append((ri,rf,ci,mid))
            callStack.append((ri,rf,mid+1,cf))
        elif dif2 >= random.randint(20,30):
            mid = (ri + rf)//2
            arr[mid][ci] = 0
            arr[mid][cf] = 0
            corners.append((mid,ci))
            corners.append((mid,cf))
            callStack.append((ri,mid,ci,cf))
            callStack.append((mid+1,rf,ci,cf))
corners = []
partitionTree2(arr,0,799,0,799,corners)
drawMaze(arr)`
