### ISSUE TITLE
Diseño de algoritmos - More

### ISSUE THREAD

**Issue by MrPool702** [MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997#6]
Se puede realizar en cualquier artefacto de diseño de algoritmos

**Comment by moisesmoreperez** [comment]
<img src="https://github.com/MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997/blob/main/TestMap.png?raw=true" alt="City Map" width="300px">

**Comment by Moisesmp75** [comment]
**Explicación**
Al tratarse de encontrar la ruta más óptima o corta entre un punto de distribución y los diversos puntos de entrega para abaratar los costos, he considerado que el Algoritmo de Dijkstra es una buena propuesta, puesto que este se basa en hallar el camino más corto entre un vértice y los conjuntos de nodos que están de por medio para llegar al destino o nodo final.

**Pseudocódigo**
    DIJKSTRA (Grafo G, nodo_fuente s)
        para u ∈ V[G] hacer
            distancia[u] = INFINITO
            padre[u] = NULL
        distancia[s] = 0
        Encolar(cola, grafo)
        mientras que cola no es vacía hacer
            u = extraer_minimo(cola)
            para v ∈ adyacencia[u] hacer
                si distancia[v] > distancia[u] + peso(u,v) hacer
                    distancia[v] = distancia[u] + peso(u,v)
                    padre[v] = u
                    Actualizar(cola,distancia,v)
