### ISSUE TITLE
Diseño de algoritmos - Cahuas

### ISSUE THREAD

**Issue by MrPool702** [MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997#7]
Se puede realizar en cualquier artefacto de diseño de algoritmos

**Comment by Miguel445Ar** [comment]
Mi propuesta de algoritmo para solucionar este problema sería un algoritmo que me permita encontrar el camino más óptimo en distancia y, por ende, en coste de gasolina y otros insumos. Sin embargo, dicho algoritmo no debería visitar tantos nodos como Dijkstra,ya que sería muy costoso porque hay que tener en cuenta que son casi 6000 nodos los que deberíamos tomar en cuenta. En consecuencia, propongo emplear una función de heurística que nos permita darnos cuenta de que nodos vecinos merecen la pena ser evaluados. De este modo, solo recorreríamos una fracción de nuestro espacio de búsqueda. Existen diferentes algoritmos que aplican este principio como el A* y sus variaciones y derivados. Entre ellos se encuentra el D* Lite el cual es un algoritmo de búsqueda incremental informada, y es incluso más rápido que el A*. Por ello, me basaría en la teoría de este algoritmo para poder diseñar el mio.
[https://es.wikipedia.org/wiki/D*#:~:text=D*%20Lite%E2%80%8B%20es%20un,%E2%80%8B](url)
Mi algoritmo consistiría en tener una cola de prioridad que , a diferencia de dijkstra, no solo empleará una función de evaluación de coste, sino también se le sumará a dicho resultado una función heurística que estime el coste desde un nodo determinado al nodo destino. De esta, forma podríamos visitar solo los nodos que merezcan más la pena. Una idea preliminar de función heirística podría ser la distancia de Manhattan, ya que el camino de un punto a otro en una ciudad no suele ser en línea recta.
 
A continuación, seguiría un procedimiento similar al algoritmo de dijkstra con la diferencia de que del nodo en donde se encuentre el algoritmo solo se moverá a aquel cuya función de evaluación es la menor, es decir, f(n) = g(n) + h(n), donde g es el coste del nodo y h es el coste estimado desde dicho nodo hasta el nodo destino.
Además el análisis asintótico sería similar a Dijkstra, es decir un O(n^2); sin embargo, en ejecución sería notablemente superior.
