### ISSUE TITLE
Diseño de algoritmos - Escobedo 

### ISSUE THREAD

**Issue by MrPool702** [MrPool702/wv72_tf_20191c036_201924132_202016505_201910358_20171e997#8]
Se puede realizar en cualquier artefacto de diseño de algoritmos

**Comment by jordori** [comment]
![TestMap](https://user-images.githubusercontent.com/66281793/135771234-9607cdc7-9fb6-4b83-820d-cd79d7225110.png)

**Comment by jordori** [comment]
Como se nos pide encontrar el recorrido mas corto entre un punto de distribución y los diversos puntos de entrega para abaratar los costos, he considerado que el Algoritmo de Floyd-Warshalles una buena propuesta, puesto que este es un algoritmo de análisis sobre grafos para encontrar el camino mínimo entre grafos. El algoritmo encuentra el camino entre todos los pares de vértices en una única ejecución.

Pseudocodigo
/*Suponemos que la función Arista devuelve el coste del camino que va de i a j

También suponemos que n es el número de vértices y pesoArista(i,i) = 0*/

int camino[][];
/*Una matriz bidimensional. En cada paso del algoritmo, camino[i][j] es el camino mínimo  de i hasta j usando valores intermedios de (1..k-1). Cada camino[i][j] es inicializado */

procedimiento FloydWarshall ()
    para k: = 0 hasta n − 1
       camino[i][j] = mín ( camino[i][j], camino[i][k]+camino[k][j])
    fin para
